### PR TITLE
Fix createReactNativeComponentClass for RN < 0.50

### LINKED ISSUE #498: undefined is not an object (evaluating 'validAttributes[propKey]')
Facing this on `6.0.0-rc12`:
`undefined is not an object (evaluating 'validAttributes[propKey]')`
`Cannot read property 'children' of undefined`

<div>

</div>

react-native 0.48.2

### PR DESCRIPTION
**Pull request by brunolemos**
Fix #498 

Sorry, the last PR #486 was merged with this bug.

A patch fix needs to be deployed cc @magicismight 

Current workaround: `npm install --save brunolemos/react-native-svg#rn-50-fix`

### CODE REVIEW

File: lib/createReactNativeComponentClass.js [hunk 1]
```diff
@@ -3,4 +3,4 @@ import createReactNativeComponentClass from 'react-native/Libraries/Renderer/shi
 export default (uiViewClassName, getViewConfig) =>
   createReactNativeComponentClass.length >= 2
     ? createReactNativeComponentClass(uiViewClassName, getViewConfig)
-    : createReactNativeComponentClass(getViewConfig)
+    : createReactNativeComponentClass(getViewConfig())
```
Comment (brunolemos) [inline lib/createReactNativeComponentClass.js]: ^ This was the problem

**Comment by brunolemos** [comment]
@magicismight thanks!
